### ISSUE TITLE
come fare in modo di ingrandire un immagine con un pop up dentro una pagina `.md`

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/guida-umap#10]
prendendo spunto da questo esempio:
[https://hfcqgis.opendatasicilia.it/calcolatore_campi/field_calc/#fnref:2](https://hfcqgis.opendatasicilia.it/calcolatore_campi/field_calc/#fnref:2)
in cui l'immagine al clic si apre in un pop up e si richiude rientrando nella pagina di prima,
chiedo quali sono le istruzioni da seguire per rendere possibile questa funzione.
Grazie

**Comment by aborruso** [comment]
@cirospat la assegno a @gbvitrano , sono cose che fa lui

**Comment by gbvitrano** [comment]
@cirospat se passa troppo tempo e non rispondo... citofona su telegram :-)

**Comment by cirospat** [comment]
risolto da @gbvitrano 
grazie

chiudo issue
