### ISSUE TITLE
mappa come sovrapposizione personalizzata 

### ISSUE THREAD

**Issue by giamplo-git** [opendatasicilia/guida-umap#11]
### Descrizione

Salve, piú che un suggerimento é una richiesta: si puó mettere una mappa sovrapposta, come raster, magari semitrasparente con questo comando? Dovrá essere georiferita, immagino. Grazie

### URL di riferimento

https://opendatasicilia.github.io/guida-umap/creare/sovrapposizione-personalizzata/

**Comment by aborruso** [comment]
Ciao @giamplo-git deve essere una mappa resa disponibile come mappa a tiles. In questo vecchissimo filmato un esempio https://www.youtube.com/watch?v=J7Vqe67nJKY

**Comment by giamplo-git** [comment]
Ciao. Grazie per la sollecitudine, ma il link a yt mi restituisce un video sulla Ferragni?
--
Inviato da Libero Mail

**Comment by aborruso** [comment]
Incollo nuovamente https://youtu.be/FeUayR8t8oM

**Comment by giamplo-git** [comment]
Ora lo vedo, ma è senza audio. 
Per quel che ho visto però, lo sto guardando dal cellulare, mi pare si riferisca allo mappa di sfondo .
 Io vorrei mettere solo uno stralcio di una mappa antica scansionata , sovrapposta sulla mappa di base di OSM , o altro di quelle disponibili. 
--
Inviato da Libero Mail

**Comment by aborruso** [comment]
E perché dovrebbe avere l'audio?

La mappa inserita in questo modo, va sopra lo sfondo che hai impostato. Puoi impostare i livelli di zoom a cui è visibile e la trasparenza

**Comment by giamplo-git** [comment]
Bè pensavo fosse con l'audio..😁 e mi pareva fosse il mio cellulare a non riprodurlo correttamente. Ok, grazie ancora, poi me lo guardo con calma sul PC. Ciao
--
Inviato da Libero Mail

**Comment by gbvitrano** [comment]
Certo che si può fare, dal menù principale seleziona **sovrapposizione personalizzata** o **Custom overlay**
![2024-01-13_13h52_13](https://github.com/opendatasicilia/guida-umap/assets/20488693/7908f55d-83b2-4f0b-9db4-d8fda738234a)

![2024-01-13_13h50_13](https://github.com/opendatasicilia/guida-umap/assets/20488693/a1c24814-ccb5-4c20-9c5d-5a60336d5736)
pel trasparenza usa il cursore **opacità** **opacity**
![2024-01-13_13h50_31](https://github.com/opendatasicilia/guida-umap/assets/20488693/0c3fa8a3-15cb-4906-aa21-e754e1d111ba)

**Comment by gbvitrano** [comment]
Per georeferenziare la tua mappa storica usa https://mapwarper.net/  dopo aver georeferenziato la mappa puoi ottenere le tiles utili per la sovrapposizione
indirizzo tipo **https://mapwarper.net/maps/tile/TUA-MAPPA/{z}/{x}/{y}.png**

**Comment by giamplo-git** [comment]
Perfetto! Grazie. Solo una cosa: l' URL di mapwarper è come nel caso della mappa di sfondo personalizzata? 
--
Inviato da Libero Mail

**Comment by giamplo-git** [comment]
Ok! 😃
--
Inviato da Libero Mail

**Comment by gbvitrano** [comment]
> Perfetto! Grazie. Solo una cosa: l' URL di mapwarper è come nel caso della mappa di sfondo personalizzata? -- Inviato da Libero Mail

si,  ma umap accetta solo mappe tiles, qualsiasi mappa devi sovrappore deve essere di TILES  {z}/{x}/{y}.png e  https://mapwarper.net/ è un servizio gratuito che ti consente di ottenere in output anche una mappa tiles

**Comment by cirospat** [comment]
@giamplo-git 
una volta che hai rettificato la tua mappa su [https://mapwarper.net/](https://mapwarper.net/) (da un formato JPG o PDF),  vai alla pagina "EXPORT" del menù, come ad es. qui: [https://mapwarper.net/maps/73271#Export_tab](https://mapwarper.net/maps/73271#Export_tab) e prendi l'URL che trovi al rigo `Tiles (Google/OSM scheme)` e lo vai a copiare sul menù di uMap, come ti ha indicato dettagliatamente @gbvitrano .
Il gioco è fatto.

![image](https://github.com/opendatasicilia/guida-umap/assets/3757525/8dbce997-79f9-4c38-b94d-ad6253019cc9)

**Comment by gbvitrano** [comment]
Guida aggiornata

**Comment by giamplo-git** [comment]
Ok. Grazie 
--
Inviato da Libero Mail
