### ISSUE TITLE
Creare struttura di base del sito

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/guida-umap#3]

**Comment by gbvitrano** [comment]
La struttura dovrebbe seguire i menù di umap, in stile Martino 
![2023-10-15_16h06_07](https://github.com/opendatasicilia/guida-umap/assets/20488693/0de020cd-025a-46a7-aa51-a16dbfb7da14)

**Comment by gbvitrano** [comment]
deve esserci una sezione blog dove mettere eventuali ricette?

**Comment by cirospat** [comment]
> deve esserci una sezione blog dove mettere eventuali ricette?

lavoriamo su **[questo Google doc condiviso](https://docs.google.com/document/d/1qIJGzUK9rNW52Z10AzFObepJou8d7bMxAD3-mRUjG2Y/edit#heading=h.7rxcce1xruiz)**

**Comment by aborruso** [comment]
Tenere conto che esiste questa:
<https://wiki.openstreetmap.org/wiki/IT:UMap/Guide>

A me non piace molto, ma possiamo prenderne spunto.

**Comment by cirospat** [comment]
credo che la struttura del sito guida sia già costruita
