### ISSUE TITLE
Abilitare le social cards

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/guida-umap#5]
https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=soci

**Comment by cirospat** [comment]
@gbvitrano 
appena puoi,
2 minuti per questa cosa
grazie

**Comment by gbvitrano** [comment]
Plugin social card attivata. qui la giuda [https://squidfunk.github.io/mkdocs-material/plugins/social/](https://squidfunk.github.io/mkdocs-material/plugins/social/
)  noi possiamo modificare solo le cartelle di e poco altro, la modifica del layout e i colori sono solo per insiders

![23cb691dd309d36657f894bcc680665c](https://github.com/opendatasicilia/guida-umap/assets/20488693/a963df02-a8e7-44a5-8a02-b5dfb297892b)
