### ISSUE TITLE
Aggiungere un modo di fare una proposta di modifica

### ISSUE THREAD

**Issue by cirospat** [opendatasicilia/guida-umap#8]
Sarebbe utile inserire nel progetto la funzione: **Was this page helpful?** 
pe rilevare il feedback.

Istruzioni sono disponibili a questa pagina:
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=page+helpful%3F#was-this-page-helpful

**Comment by aborruso** [comment]
Io non l'ho mai attivato, perché secondo me la cosa essenziale è abilitare un tasto che ti fa aprire una issue sulla pagina.
E se ti garba lo faccio.

Per abilitare questa feature, bisogna abilitare google analytics, che io non abilito mai, perché ci vuole la laurea in regole che io spesso trovo troppo complicate e inutili.

Se @gbvitrano abilita analytics, io poi abilito questo.

**Comment by cirospat** [comment]
Abilitare un tasto che ti fa aprire una issue sulla pagina sarebbe utile.

Il resto (Google analytics) possiamo anche lasciarlo stare per me.

**Comment by aborruso** [comment]
Ecco una prima versione??

Per ora è basata su un google form, ma poi attivo tutto qui su github, pubblico e visibile.

![image](https://github.com/opendatasicilia/guida-umap/assets/30607/b523e387-5b50-40f3-8fc1-e734a2227a29)

**Comment by cirospat** [comment]
ho notato che in alcune pagine cliccando su "`Hai un suggerimento`" a destra in alto, non si apre la pagina dell'issue ma si apre un altra pagina della guida uguale a quella di prima.

**Comment by aborruso** [comment]
Dovrebbe essere risolto @cirospat

**Comment by cirospat** [comment]
buongiorno @aborruso 
ho visto che ora cliccando sul link nel menù di destra "`Hai un suggerimento`" si apre correttamente la pagina dell'issue.

Ho notato che in alcune pagine il link "`Hai un suggerimento`" appare anche nel menù di sinistra, ma non in tutte.

Guarda queste due:

1. https://opendatasicilia.github.io/guida-umap/creare/index-scelte/ (qui c'è anche a sinistra)
2. https://opendatasicilia.github.io/guida-umap/creare/proprieta-preimpostate/ (qui invece a sinistra non appare)


Ho dato un colore al link in maniera che si nota immediatamente:
![image](https://github.com/opendatasicilia/guida-umap/assets/3757525/de00fd89-4b88-409f-b401-fedd27615a47)

**Comment by aborruso** [comment]
@cirospat spengo tutto, non ci posso dedicare altro tempo per ora.

Nelle prossime settimane si fa. Purtroppo è documentato (per me) male

**Comment by cirospat** [comment]
ok

**Comment by aborruso** [comment]
@cirospat dovrebbe essere ok

**Comment by aborruso** [comment]
> [opendatasicilia.github.io/guida-umap/creare/proprieta-preimpostate](https://opendatasicilia.github.io/guida-umap/creare/proprieta-preimpostate/) (qui invece a sinistra non appare)

Appare soltanto dove c'è un TOC

**Comment by cirospat** [comment]
> > [opendatasicilia.github.io/guida-umap/creare/proprieta-preimpostate](https://opendatasicilia.github.io/guida-umap/creare/proprieta-preimpostate/) (qui invece a sinistra non appare)
> 
> Appare soltanto dove c'è un TOC

**ovviamente quando hai tempo**:
o c'è in tutte le pagine (a prescindere dal TOC) o in nessuna pagina

**Comment by aborruso** [comment]
Così ci dovremmo essere @cirospat 

![image](https://github.com/opendatasicilia/guida-umap/assets/30607/bef94d9c-2188-4fae-98fb-6ebbdafb2b6f)

**Comment by cirospat** [comment]
mi sembra ottima come soluzione, migliore della precedente!!!!!!!!!!!!
Grazie
